discord:
  botkey:
  channel:
  qlength: 64
  waitms: "500ms"

ironrealms:
  apiurl: "https://api.achaea.com"
  character:
  password:
  defencechannels:
  offencechannels:
  citychannel:

database:
  connection: "user=ada password=ada dbname=ada-bot sslmode=disable"

settingsfile: settings.yaml
