discord:
  botkey: "Paste the Bot User's token from https://discordapp.com/developers/applications/me here"
  channel:
    - "deathsightChannelID_1"
    - "deathsightChannelID_2"
  qlength: 64
  waitms: "500ms"

ironrealms:
  apiurl: "https://api.achaea.com"

database:
  connection: "user=ada password=ada dbname=ada-bot sslmode=disable"

settingsfile: settings.yaml
