discord:
  botkey: "ID_here"
  channel:
    - "985769725441212426"
  qlength: 64
  waitms: "500ms"

ironrealms:
  apiurl: "https://api.starmourn.com"

database:
  connection: "user=ada password=ada dbname=ada-bot sslmode=disable"

settingsfile: settings.yaml
