discord:
  botkey: "OTg1NzY1NDg3MzgyMjM3MjE1.G5hAK0.9UQWPPLstUxzdjhQcbmNz3k5tEU30aLYqDCjeo"
  channel:
    - "985769725441212426"
  qlength: 64
  waitms: "500ms"

ironrealms:
  apiurl: "https://api.starmourn.com"

database:
  connection: "user=ada password=ada dbname=ada-bot sslmode=disable"

settingsfile: settings.yaml
